### ISSUE TITLE
possible error compiling with visual studio

### ISSUE THREAD

**Issue by austinerees** [ZeppSav/BEMUse#2]
hi,
Greetings. please forgive me if my question is very basic .I am having a hard time compiling and running the code in visual studio 2019. although they asked for the eigen libraries which I could only get 3.3.4 version to include and since i am been been rusty with C++,i could could see that these dependencies wouldn't make them run which i feel could be easier to fix but i have no idea except been guided.. I could not get it to work. I would be grateful if you could give  a few steps on how to install it. I use windows machine and visual studio 19. Thank you in advance.

**Comment by ZeppSav** [comment]
Hello,
To be completely honest I never compiled with VS. As I wrote in the README, I testing compilation using gcc and am unsure how much help I can give you without trying to compile with VS myself. 

The last version of eigen I used to compile was 3.3.9, so perhaps this is creating a problem. You should be able to pull the newest version just by cloning the [gitlab ](https://gitlab.com/libeigen/eigen) repo. I might be able to help you a little if you send your log file.

**Comment by austinerees** [comment]
Thank you very much for your responses. Could you give me a basic idea and steps on how to compile and run it on windows 10?thank you in advance

**Comment by ZeppSav** [comment]
If you want to compile quickly and easily I would suggest getting the newest version of [Qt Creator](https://www.qt.io/product/development-tools) with the 64-bit mingw compilation executables. There is a Qt project file in the BEMUse repo which is basically set up to allow you to directly compile easily with Qt. Alternatively, you could just use the executables on the release page and if there is anything you would like changed, then feel free to request it and I will try to put this into the next release.

**Comment by austinerees** [comment]
thank you so very much. I will use the directly executables and change the geometry. will contact you should i have any issues

**Comment by austinerees** [comment]
thank you so very much.The executable is working fine. could you give me a
copy of this document "

   - Saverin, J., Grueter, L. *Quadrature Schemes for the Integration of
   the Free-Surface Greens Function within the Open-Source Boundary Element
   Method Library BEMUse*, Proceedings of the ASME 2022 41st International
   Conference on Ocean, Offshore and Arctic Engineering. June 2022, Hamburg,
   Germany." .I would like to read it as i find it interesting.
   - Kind regards,

**Comment by ZeppSav** [comment]
That publication is under copyright from OMAE, an entity of ASME. Sharing it here would be a breach of copyright. Feel free to send me an email at my work email which is at the top of every header file in the BEMUse source code.

**Comment by austinerees** [comment]
Thank you for your reply.can i get your email address?I'd like to ask a few
questions regarding the implementation of the hydrodynamic solver.

Best regards,

**Comment by ZeppSav** [comment]
As I stated in the previous message, my work email is at the top of every header file in the source code of BEMUse. You will find my email there.

**Comment by austinerees** [comment]
Ok, thanks for the clarification.

**Comment by austinerees** [comment]
Hello,
Greetings
I have been able to open the program in qt finally! But i can't get the
eigen library. Could you please point me in the right direction on how to
get the right version?
Thank you
